import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

const archivo = localFont({
  src: [
    {
      path: '../public/fonts/Archivo-Variable.ttf',
      style: 'normal',
    },
    {
      path: '../public/fonts/Archivo-VariableItalic.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-archivo',
  display: 'swap',
})

const clashDisplay = localFont({
  src: '../public/fonts/ClashDisplay-Variable.ttf',
  variable: '--font-clash-display',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background overflow-scroll text-foreground p-3 h-screen max-h-screen flex flex-col [&:has(.no-preview-padding)]:p-0 ${archivo.variable} ${clashDisplay.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
