import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import { CommandMenuProvider } from "@/providers/command-menu-provider"
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/providers/theme-provider"

const archivo = localFont({
  src: [
    {
      path: "../public/fonts/Archivo-Variable.ttf",
      style: "normal",
    },
    {
      path: "../public/fonts/Archivo-VariableItalic.ttf",
      style: "italic",
    },
  ],
  variable: "--font-archivo",
  display: "swap",
})

const clashDisplay = localFont({
  src: "../public/fonts/Sora.ttf",
  variable: "--font-heading",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster />
          <CommandMenuProvider>
            <div
              id="body-scroll-container"
              className={`relative flex h-screen max-h-screen flex-col overflow-scroll bg-secondary p-2! text-foreground antialiased dark:bg-background [&:has(.no-preview-padding)]:p-0! ${archivo.variable} ${clashDisplay.variable}`}
            >
              {children}
            </div>
          </CommandMenuProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
